[default]
database_hostname = localhost
database_port = 5432
database_name =
database_username =
database_password =

username = ef_user

working_directory = ./
log_directory = ./log/

source = file
log_level = INFO
approximate = false
overwrite = false

start_date =
end_date =
label =